name: lapa
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - samtools
  - ucsc-bedtobigbed
  - seqkit
  - sra-tools
  - star
  - pip:
    - snakemake
    - biopython
    - jupyter
    - notebook
    - pytest
    - cython
    - pyfaidx
    - seaborn
    - snakemk_util
    - git+https://github.com/mortazavilab/lapa.git#egg=lapa
    - adjustText
