name: lapa
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip
  - samtools
  - ucsc-bedtobigbed
  - seqkit
  - star
  - minimap2
  - snakemake
  - pip:
    - pdf2image
    - biopython
    - jupyter
    - notebook
    - pytest
    - cython
    - pyfaidx
    - seaborn
    - snakemk_util
    - adjustText
    - patchworklib
    - sklearn
    - -e .
