genome:
  fasta:
    hg38: data/resources/common/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta
    mm10: data/resources/common/GRCm38.primary_assembly.genome.fasta
      
  gtf_raw:
    hg38: data/resources/common/gencode.v38.annotation.gtf
    mm10: data/resources/common/gencode.vM25.annotation.gtf
    
  gtf:
    hg38: data/resources/common/gencode.v38.annotation.utr_fix.gtf
    mm10: data/resources/common/gencode.vM25.annotation.utr_fix.gtf
    
  star_index:
    mm39: data/resources/common/lrgasp_mouse_star_index/
    hg38: data/resources/common/lrgasp_human_star_index/

common:
  chrom_sizes: data/results/common/{genome}.chrom_sizes
  tes: data/results/common/{genome}_tes.csv
  gene_id_name_mapping: data/results/common/{genome}_gene_id_name_mapping.csv

lrgasp:
  config: configs/rnaseq-data-matrix.tsv

encode: 
  fastq: data/resources/encode/fastq/{encode_id}.fastq.gz
  fastq_polyA: data/results/encode/fastq_polyA/{encode_id}_polyA.fastq.gz
  bam: data/resources/encode/bam/{encode_id}.bam

  fastq_read_count: data/results/encode/read_count/{encode_id}_fastq.txt
  fasta_read_count: data/results/encode/read_count/{encode_id}_fasta.txt
  bam_read_count: data/results/encode/read_count/{encode_id}_bam.txt

talon:
  read_annot: data/resources/talon/{sample}_{library_prep}_{platform}_read_annot.tsv
  gtf: data/resources/talon/{sample}_{library_prep}_{platform}.gtf
  abundance: data/resources/talon/{sample}_{library_prep}_{platform}_abundance_filtered.tsv
  gtf_corrected: data/results/talon/{sample}_{library_prep}_{platform}_{counting}_corrected.gtf
  
lapa:
  samples: data/results/lapa/{sample}/{library_prep}_{platform}.csv
  lapa_dir: data/results/lapa/{sample}/{library_prep}_{platform}_{counting}/
  lapa_tss_dir: data/results/lapa_tss/{sample}/{library_prep}_{platform}_{counting}/  
  lapa_quantseq_dir: data/results/lapa/{sample}/quantseq_Illumina_end/
  
quantseq:
  fastq: data/resources/quantseq/fastq/{sample}_rep{rep}.fastq.gz
  
  bam: data/results/quantseq/bam_tail/{sample}_rep{rep}/Aligned.sortedByCoord.out.bam
  bam_end: data/resources/quantseq/bam_end/{sample}_rep{rep}/polyA/Aligned.sortedByCoord.out.bam

  fastq_read_count: data/results/quantseq/read_count/{sample}_rep{rep}_fastq.txt
  bam_read_count: data/results/quantseq/read_count/{sample}_rep{rep}_bam.txt

  polya_atlas: data/resources/quantseq/polya_atlas/{sample}/{sample}rep{rep}.bed.gz

short_rnaseq:
  WTC11:
    se:
      - ENCFF492PIB
      - ENCFF365HXR
      - ENCFF621NOL
      - ENCFF738DHG
      - ENCFF235BRN
      - ENCFF742FDJ
      
  bam: data/results/short_read/{sample}/{encode_id}/Aligned.sortedByCoord.out.bam
  bam_read_count: data/resources/short_read/read_count/{sample}_{encode_id}_bam.txt

  gene_exp: data/resources/short_read/gene_exp/{sample}.tsv

c2c12:
  read_annot_bulk_sc: data/resources/c2c12/c2c12_bulk_sc_talon_read_annot.tsv
  read_annot_bulk: data/resources/c2c12/c2c12_bulk_talon_read_annot.tsv
  read_annot_sc: data/resources/c2c12/c2c12_sc_talon_read_annot.tsv
  abundance: data/resources/c2c12/bulk_talon_abundance.tsv

  lapa_bulk_dir: data/results/c2c12/lapa/bulk/
  lapa_bulksc_dir: data/results/c2c12/lapa/bulksc/

  diff_polya: data/results/c2c12/diff_polya.csv
  
cage:
  bed: data/resources/cage/{geo_id}.count.bed.gz
  # https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE185917

  WTC11:
    - GSM5625727_WTC11-1_rep1
    - GSM5625728_WTC11-1_rep2
    - GSM5625729_WTC11-1_rep3
    - GSM5625730_WTC11-3_rep1
    - GSM5625731_WTC11-3_rep2
    - GSM5625732_WTC11-3_rep3