name: lapa
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip=21.2
  - python=3.7
  - pip:
    - cython==0.29.28
    - sphinx==4.4.0
    - sphinx-autoapi==1.8.4
    - sphinx-click==3.1.0
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-napoleon==0.7
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5